name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"

    - name: Build Docker Image
      run: |
        echo "Construyendo las imagenes"
        docker build -t minoshia/docker-graphql:0.0.2 .
        docker build -t minoshia/docker-graphql:latest .
        echo "Imagenes construidas"

    - name: Push Docker Image
      run: |
        echo "Publicando las imagenes"
        docker push minoshia/docker-graphql:0.0.2
        docker push minoshia/docker-graphql:latest
        echo "Imagenes publicadas"
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
